#! /bin/sh

name=base-files
skip_pkg_check=yes
version=0.0
revision=1
source_dir="base-files"

package() {
    cp -rpv ${source_dir}/. "${dest_dir}"/
    install -dv -m 1777 "${dest_dir}"/tmp "${dest_dir}"/var/tmp
}
